### ISSUE TITLE
Adjust num_classes to custom dataset

### ISSUE THREAD

**Issue by cristof-r** [MasterBin-IIAU/UNINEXT#17]
I am training your model for instance segmentation on my own dataset and saw that there are 3 mentions of num_classes in the config:

```
MODEL:
  DDETRS:
    NUM_CLASSES: null
  RETINANET:
    NUM_CLASSES: 80
  ROI_HEADS:
    NUM_CLASSES: 80
  SEM_SEG_HEAD:
    NUM_CLASSES: 54
```

Which have to be adjusted for the instance segmentation task?
Anything else has to be adjusted?

Thank you very much for this fascinating project.
